
coder:
  coderImage: "ghcr.io/eoap/dev-platform-eoap/eoap-coder:0.1.0"
  workspace: quickwin
  storageClassName: standard
  workspaceStorage: 20Gi
  securityContext:
    privileged: true
  serviceType: ClusterIP

calrissian:
  enabled: True
  storage: 20Gi
  storageClassName: standard
  imagePullSecrets:
    - kaniko-secret

coderResources:
  limits:
    cpu: '2'
    memory: '6442450944'
  requests:
    cpu: '1'
    memory: '4294967296'

skaffold:
  enabled: False

daskGateway: 
  enabled: False
  daskGatewayUrl: ""
  image: ""

kaniko:
  enabled: False
